# Generated by Django 4.2.9 on 2024-03-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='comments',
        ),
    ]
