# Generated by Django 4.2.9 on 2024-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_remove_audiomodel_comments_remove_bookmodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodel',
            name='thumbnail_photo',
            field=models.FileField(null=True, upload_to='audio_photo/'),
        ),
    ]
