# Generated by Django 4.2.9 on 2024-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_audiomodel_audio_status_bookmodel_book_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomodel',
            name='audio_status',
            field=models.CharField(choices=[('PROGRESS', 'В прогрессе'), ('CANCEL', 'Отменен'), ('SUCCESS', 'Успешно')], default='PROGRESS', max_length=70),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='book_status',
            field=models.CharField(choices=[('PROGRESS', 'В прогрессе'), ('CANCEL', 'Отменен'), ('SUCCESS', 'Успешно')], default='PROGRESS', max_length=70),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_status',
            field=models.CharField(choices=[('PROGRESS', 'В прогрессе'), ('CANCEL', 'Отменен'), ('SUCCESS', 'Успешно')], default='PROGRESS', max_length=70),
        ),
    ]
