# Generated by Django 4.2.9 on 2024-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_audiomodel_audio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail_photo',
            field=models.FileField(null=True, upload_to='video_photos/'),
        ),
    ]
