# Generated by Django 4.2.9 on 2024-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_videomodel_thumbnail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail_photo',
            field=models.FileField(blank=True, null=True, upload_to='video_photos/'),
        ),
    ]
