# Generated by Django 4.2.9 on 2024-03-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_alter_videomodel_thumbnail_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
