# Generated by Django 4.2.9 on 2024-03-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='likes',
        ),
    ]
